version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
  redis:
    image: redis
    command: redis-server --requirepass courier123
    ports:
      - 6379:6379

volumes:
  mongodata: {}